page_title                                : Trackable. Today.

# App Info
ios_app_id                                : 6458344263
ios_app_country                           : us

appstore_link                             : https://apps.apple.com/app/trackables/id6458344263

app_icon                                  : assets/appicon.png
app_name                                  : Trackables
app_price                                 : Free
app_description                           : Your personal data organizer. Never forget a thing.

enable_smart_app_banner                   : true



# Feature List
features                                  :

  - title                                 : Trackables
    description                           : Collect data in one place. Monitoring weight? Tracking electricity meter? Periodically handling taxes? Anything will do.
    fontawesome_icon_name                 : plus
    
  - title                                 : Reminders
    description                           : Create a schedule for periodic tracking and the app will remind you about it.
    fontawesome_icon_name                 : bell

  - title                                 : To Do Organizer
    description                           : All due and upcoming trackables organized in a simple "To Do" list. Never forget a thing.
    fontawesome_icon_name                 : clock

  - title                                 : Chart Preview
    description                           : Group your countable data by day/week/month/year and observe the trends. Make sure you are on the right track.
    fontawesome_icon_name                 : map



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - trackable-today.xcodeproj

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
